{% set name = "google-cloud-datastore" %}
{% set version = "1.15.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-datastore-{{ version }}.tar.gz
  sha256: dadca1631088b7a737f311df87574a417f254ce71d6a98080f36f35bdc96b30f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-cloud-core >=1.4.0,<3.0dev
    - protobuf <4.0.0dev

test:
  imports:
    - google
    - google.cloud
    - google.cloud.datastore
    - google.cloud.datastore_v1
    - google.cloud.datastore_admin_v1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-datastore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Datastore
  description: |
    Google Cloud Datastore API is a fully managed, schemaless database for
    storing non-relational data. Cloud Datastore automatically scales with
    your users and supports ACID transactions, high availability of reads
    and writes, strong consistency for reads and ancestor queries, and
    eventual consistency for all other queries.
  doc_url: https://googleapis.github.io/google-cloud-python/latest/datastore/index.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python

extra:
  recipe-maintainers:
    - xylar
    - mathiaseitz
    - trendelkampschroer
    - parthea
