travis:
  secure:
    BINSTAR_TOKEN: xdcGjEY7Llujlb913IPZf3VXrbefPZCXm9bHhhoikSwjzggW6RAiVPr/hvcMfoWkEjYCD65Zkojn5VaOdDFkYByrxOX9dYIrTaROTm5KDz4Rss/6vzJ6ZOJry/wW4ObSK4dfK2s+OimZyVul0U8DxXU9cuiQjpdgfoC0cLiYG12G4RRapYyD4160HvXRVbND+1riP7ndokGLTgVzevW1y6L2HXwTUtM9qIHFM8G9szeZtMpPz9pKpWbs0i+uZMmXFFZFpVMOuTVKoZJYo+FuV15j510j2ZHRuajNLDjS9hUY4yrpc+WoKwiRoKK+KIPUwmMcbt8ip2hgBbNdVwixTgMBTm2A4erMWz5ork7eT9qAb4bMB8oBCPKtgLqsv7jQTemmyJF6z6VgjjNnxdw8TUguKtADF6oMxHpwOXLF9rc5o/9wm2t5qiK0ZBRW4ijVJbXDLX8ea1n645Mr3vkP/H3YPAYfMBOa/fpuEB2TbouQ/tJhwNlTypWKDB5UC1PcGu8gl97jqehG/PqFzgE8ykINYCrq8Aa+EP7cHrrPRZJGt1zKT7AQ5qA/T1gXSq4CjXhDh3e5ezC2CObLELZmrBy6UjoTZp+hEnEJBs+a+Va9up46v7haCKiCnd1umUYp83U04ZSH3/7GHSmYVHTRosRArOjUHY6NQtBBwWAQ8Bk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
